/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TrimWithMarketAndYears'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TrimWithMarketAndYears'));
  } else {
    // Browser globals (root is window)
    if (!root.ws_api_client) {
      root.ws_api_client = {};
    }
    root.ws_api_client.ModelWithTrims = factory(root.ws_api_client.ApiClient, root.ws_api_client.TrimWithMarketAndYears);
  }
}(this, function(ApiClient, TrimWithMarketAndYears) {
  'use strict';




  /**
   * The ModelWithTrims model module.
   * @module model/ModelWithTrims
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelWithTrims</code>.
   * @alias module:model/ModelWithTrims
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>ModelWithTrims</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelWithTrims} obj Optional instance to populate.
   * @return {module:model/ModelWithTrims} The populated <code>ModelWithTrims</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('slug')) {
        obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('start_year')) {
        obj['start_year'] = ApiClient.convertToType(data['start_year'], 'String');
      }
      if (data.hasOwnProperty('end_year')) {
        obj['end_year'] = ApiClient.convertToType(data['end_year'], 'String');
      }
      if (data.hasOwnProperty('vehicles')) {
        obj['vehicles'] = ApiClient.convertToType(data['vehicles'], [TrimWithMarketAndYears]);
      }
    }
    return obj;
  }

  /**
   * Model name (e.g. `Outlander`)
   * @member {String} slug
   */
  exports.prototype['slug'] = undefined;
  /**
   * Model slug name (e.g. `outlander`)
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Model production start year. It should be 'integer' but it is used as 'string' by historical reasons.
   * @member {String} start_year
   */
  exports.prototype['start_year'] = undefined;
  /**
   * Model production end year. It should be 'integer' but it is used as 'string' by  historical reasons.  It equals to the __*`current year + 1`*__ if it is still in production.
   * @member {String} end_year
   */
  exports.prototype['end_year'] = undefined;
  /**
   * @member {Array.<module:model/TrimWithMarketAndYears>} vehicles
   */
  exports.prototype['vehicles'] = undefined;



  return exports;
}));


