/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ws_api_client) {
      root.ws_api_client = {};
    }
    root.ws_api_client.Pressure = factory(root.ws_api_client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Pressure model module.
   * @module model/Pressure
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Pressure</code>.
   * Tire pressure in different units (can be __*&#x60;null&#x60;*__)
   * @alias module:model/Pressure
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Pressure</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Pressure} obj Optional instance to populate.
   * @return {module:model/Pressure} The populated <code>Pressure</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bar')) {
        obj['bar'] = ApiClient.convertToType(data['bar'], 'Number');
      }
      if (data.hasOwnProperty('psi')) {
        obj['psi'] = ApiClient.convertToType(data['psi'], 'Number');
      }
      if (data.hasOwnProperty('kPa')) {
        obj['kPa'] = ApiClient.convertToType(data['kPa'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Pressure, bar (e.g. `2.4`)
   * @member {Number} bar
   */
  exports.prototype['bar'] = undefined;
  /**
   * Pressure, psi (e.g. `35`)
   * @member {Number} psi
   */
  exports.prototype['psi'] = undefined;
  /**
   * Pressure, kPa (e.g. `240`)
   * @member {Number} kPa
   */
  exports.prototype['kPa'] = undefined;



  return exports;
}));


