/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Aggregation', 'model/SizeAggregation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Aggregation'), require('./SizeAggregation'));
  } else {
    // Browser globals (root is window)
    if (!root.ws_api_client) {
      root.ws_api_client = {};
    }
    root.ws_api_client.TiresAggregation = factory(root.ws_api_client.ApiClient, root.ws_api_client.Aggregation, root.ws_api_client.SizeAggregation);
  }
}(this, function(ApiClient, Aggregation, SizeAggregation) {
  'use strict';




  /**
   * The TiresAggregation model module.
   * @module model/TiresAggregation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TiresAggregation</code>.
   * Tire width, aspect ratio, and rim diameter values aggregated by all possible model modifications
   * @alias module:model/TiresAggregation
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>TiresAggregation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TiresAggregation} obj Optional instance to populate.
   * @return {module:model/TiresAggregation} The populated <code>TiresAggregation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('aspect_ratio')) {
        obj['aspect_ratio'] = Aggregation.constructFromObject(data['aspect_ratio']);
      }
      if (data.hasOwnProperty('diameter')) {
        obj['diameter'] = Aggregation.constructFromObject(data['diameter']);
      }
      if (data.hasOwnProperty('width')) {
        obj['width'] = Aggregation.constructFromObject(data['width']);
      }
      if (data.hasOwnProperty('tire_size')) {
        obj['tire_size'] = SizeAggregation.constructFromObject(data['tire_size']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Aggregation} aspect_ratio
   */
  exports.prototype['aspect_ratio'] = undefined;
  /**
   * @member {module:model/Aggregation} diameter
   */
  exports.prototype['diameter'] = undefined;
  /**
   * @member {module:model/Aggregation} width
   */
  exports.prototype['width'] = undefined;
  /**
   * @member {module:model/SizeAggregation} tire_size
   */
  exports.prototype['tire_size'] = undefined;



  return exports;
}));


