/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ws_api_client) {
      root.ws_api_client = {};
    }
    root.ws_api_client.Trim = factory(root.ws_api_client.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Trim model module.
   * @module model/Trim
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Trim</code>.
   * @alias module:model/Trim
   * @class
   * @param name {String} Format: __*`trim (body)`*__ if both values provided, otherwise non-empty of them. (e.g. `2.0 (GG2W)`)
   * @param trim {String} Trim name. It can be empty for models created for JDM market (e.g. `2.0`, can be __*`null`*__)
   * @param body {String} Body name. Used extensively for JDM market (e.g. `GG2W`, can be __*`null`*__)
   */
  var exports = function(name, trim, body) {
    var _this = this;


    _this['name'] = name;
    _this['trim'] = trim;
    _this['body'] = body;

  };

  /**
   * Constructs a <code>Trim</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Trim} obj Optional instance to populate.
   * @return {module:model/Trim} The populated <code>Trim</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('slug')) {
        obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('trim')) {
        obj['trim'] = ApiClient.convertToType(data['trim'], 'String');
      }
      if (data.hasOwnProperty('body')) {
        obj['body'] = ApiClient.convertToType(data['body'], 'String');
      }
      if (data.hasOwnProperty('generation')) {
        obj['generation'] = ApiClient.convertToType(data['generation'], 'String');
      }
    }
    return obj;
  }

  /**
   * Combines trim and body name. Format: __*`trim+body`*__ if both values provided, otherwise non-empty of them. (e.g. `2.0+GG2W`)
   * @member {String} slug
   */
  exports.prototype['slug'] = undefined;
  /**
   * Format: __*`trim (body)`*__ if both values provided, otherwise non-empty of them. (e.g. `2.0 (GG2W)`)
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Trim name. It can be empty for models created for JDM market (e.g. `2.0`, can be __*`null`*__)
   * @member {String} trim
   */
  exports.prototype['trim'] = undefined;
  /**
   * Body name. Used extensively for JDM market (e.g. `GG2W`, can be __*`null`*__)
   * @member {String} body
   */
  exports.prototype['body'] = undefined;
  /**
   * Generation name (e.g. `III Restyling`, can be __*`null`*__)
   * @member {String} generation
   */
  exports.prototype['generation'] = undefined;



  return exports;
}));


