/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Generation', 'model/Market', 'model/Power', 'model/WheelPair'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Generation'), require('./Market'), require('./Power'), require('./WheelPair'));
  } else {
    // Browser globals (root is window)
    if (!root.ws_api_client) {
      root.ws_api_client = {};
    }
    root.ws_api_client.Vehicle = factory(root.ws_api_client.ApiClient, root.ws_api_client.Generation, root.ws_api_client.Market, root.ws_api_client.Power, root.ws_api_client.WheelPair);
  }
}(this, function(ApiClient, Generation, Market, Power, WheelPair) {
  'use strict';




  /**
   * The Vehicle model module.
   * @module model/Vehicle
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Vehicle</code>.
   * @alias module:model/Vehicle
   * @class
   * @param market {module:model/Market} 
   * @param generation {module:model/Generation} 
   * @param boltPattern {String} Bolt pattern (e.g. `5x105`, can be __*`N/A`*__)
   */
  var exports = function(market, generation, boltPattern) {
    var _this = this;

    _this['market'] = market;
    _this['generation'] = generation;

    _this['bolt_pattern'] = boltPattern;


  };

  /**
   * Constructs a <code>Vehicle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vehicle} obj Optional instance to populate.
   * @return {module:model/Vehicle} The populated <code>Vehicle</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('market')) {
        obj['market'] = Market.constructFromObject(data['market']);
      }
      if (data.hasOwnProperty('generation')) {
        obj['generation'] = Generation.constructFromObject(data['generation']);
      }
      if (data.hasOwnProperty('lock_type')) {
        obj['lock_type'] = ApiClient.convertToType(data['lock_type'], 'String');
      }
      if (data.hasOwnProperty('bolt_pattern')) {
        obj['bolt_pattern'] = ApiClient.convertToType(data['bolt_pattern'], 'String');
      }
      if (data.hasOwnProperty('power')) {
        obj['power'] = Power.constructFromObject(data['power']);
      }
      if (data.hasOwnProperty('wheels')) {
        obj['wheels'] = ApiClient.convertToType(data['wheels'], [WheelPair]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Market} market
   */
  exports.prototype['market'] = undefined;
  /**
   * @member {module:model/Generation} generation
   */
  exports.prototype['generation'] = undefined;
  /**
   * @member {module:model/Vehicle.LockTypeEnum} lock_type
   */
  exports.prototype['lock_type'] = undefined;
  /**
   * Bolt pattern (e.g. `5x105`, can be __*`N/A`*__)
   * @member {String} bolt_pattern
   */
  exports.prototype['bolt_pattern'] = undefined;
  /**
   * @member {module:model/Power} power
   */
  exports.prototype['power'] = undefined;
  /**
   * @member {Array.<module:model/WheelPair>} wheels
   */
  exports.prototype['wheels'] = undefined;


  /**
   * Allowed values for the <code>lock_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LockTypeEnum = {
    /**
     * value: "nut"
     * @const
     */
    "nut": "nut",
    /**
     * value: "bolt"
     * @const
     */
    "bolt": "bolt"  };


  return exports;
}));


