/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Pressure'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Pressure'));
  } else {
    // Browser globals (root is window)
    if (!root.ws_api_client) {
      root.ws_api_client = {};
    }
    root.ws_api_client.Wheel = factory(root.ws_api_client.ApiClient, root.ws_api_client.Pressure);
  }
}(this, function(ApiClient, Pressure) {
  'use strict';




  /**
   * The Wheel model module.
   * @module model/Wheel
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Wheel</code>.
   * @alias module:model/Wheel
   * @class
   * @param rim {String} Formatter rim size (e.g. `7Jx18 ET38`, can be __*`\"\"`*__)
   * @param tire {String} Formatted tire size (e.g. `225/55R18`, can be __*`\"\"`*__)
   * @param tireIs82series {Boolean} Is an old tire with assumed aspect ratio 82%
   */
  var exports = function(rim, tire, tireIs82series) {
    var _this = this;


    _this['rim'] = rim;
    _this['tire'] = tire;
    _this['tire_is_82series'] = tireIs82series;
  };

  /**
   * Constructs a <code>Wheel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Wheel} obj Optional instance to populate.
   * @return {module:model/Wheel} The populated <code>Wheel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tire_pressure')) {
        obj['tire_pressure'] = Pressure.constructFromObject(data['tire_pressure']);
      }
      if (data.hasOwnProperty('rim')) {
        obj['rim'] = ApiClient.convertToType(data['rim'], 'String');
      }
      if (data.hasOwnProperty('tire')) {
        obj['tire'] = ApiClient.convertToType(data['tire'], 'String');
      }
      if (data.hasOwnProperty('tire_is_82series')) {
        obj['tire_is_82series'] = ApiClient.convertToType(data['tire_is_82series'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Pressure} tire_pressure
   */
  exports.prototype['tire_pressure'] = undefined;
  /**
   * Formatter rim size (e.g. `7Jx18 ET38`, can be __*`\"\"`*__)
   * @member {String} rim
   */
  exports.prototype['rim'] = undefined;
  /**
   * Formatted tire size (e.g. `225/55R18`, can be __*`\"\"`*__)
   * @member {String} tire
   */
  exports.prototype['tire'] = undefined;
  /**
   * Is an old tire with assumed aspect ratio 82%
   * @member {Boolean} tire_is_82series
   */
  exports.prototype['tire_is_82series'] = undefined;



  return exports;
}));


