/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MakeWithModels', 'model/Vehicle'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/MakeWithModels'), require('../model/Vehicle'));
  } else {
    // Browser globals (root is window)
    if (!root.ws_api_client) {
      root.ws_api_client = {};
    }
    root.ws_api_client.SearchApi = factory(root.ws_api_client.ApiClient, root.ws_api_client.MakeWithModels, root.ws_api_client.Vehicle);
  }
}(this, function(ApiClient, MakeWithModels, Vehicle) {
  'use strict';

  /**
   * Search service.
   * @module api/SearchApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SearchApi. 
   * @alias module:api/SearchApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the searchByHfTireList operation.
     * @callback module:api/SearchApi~searchByHfTireListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MakeWithModels>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find models matching given high flotation tire
     * Get a list of model modifications that match the given tire size in high flotation sizing system
     * @param {Number} tireDiameter Tire diameter, in (e.g. &#x60;31&#x60;)
     * @param {Number} tireSectionWidth Tire section width, in (e.g. &#x60;10.5&#x60;)
     * @param {Number} rimDiameterHf Rim diameter, in (e.g. &#x60;15&#x60;)
     * @param {Object} opts Optional parameters
     * @param {String} opts.lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only
     * @param {String} opts.brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;)
     * @param {String} opts.brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;)
     * @param {String} opts.countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;)
     * @param {String} opts.countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;)
     * @param {module:api/SearchApi~searchByHfTireListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MakeWithModels>}
     */
    this.searchByHfTireList = function(tireDiameter, tireSectionWidth, rimDiameterHf, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'tireDiameter' is set
      if (tireDiameter === undefined || tireDiameter === null) {
        throw new Error("Missing the required parameter 'tireDiameter' when calling searchByHfTireList");
      }

      // verify the required parameter 'tireSectionWidth' is set
      if (tireSectionWidth === undefined || tireSectionWidth === null) {
        throw new Error("Missing the required parameter 'tireSectionWidth' when calling searchByHfTireList");
      }

      // verify the required parameter 'rimDiameterHf' is set
      if (rimDiameterHf === undefined || rimDiameterHf === null) {
        throw new Error("Missing the required parameter 'rimDiameterHf' when calling searchByHfTireList");
      }


      var pathParams = {
      };
      var queryParams = {
        'tire_diameter': tireDiameter,
        'tire_section_width': tireSectionWidth,
        'rim_diameter_hf': rimDiameterHf,
        'lang': opts['lang'],
        'brands': opts['brands'],
        'brands_exclude': opts['brandsExclude'],
        'countries': opts['countries'],
        'countries_exclude': opts['countriesExclude'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['user_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [MakeWithModels];

      return this.apiClient.callApi(
        '/search/by_hf_tire/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the searchByModelList operation.
     * @callback module:api/SearchApi~searchByModelListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Vehicle>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find OE and option fitments by model/year/trim
     * Find OE and option fitments that match the given manufacturer, model, year and trim.  **It&#39;s an alias** for _**&#x60;GET /vehicles/&#x60;**_ method
     * @param {String} make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;)
     * @param {String} model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;)
     * @param {Number} year You can use _**&#x60;GET /years/&#x60;**_ to get possible years (e.g. &#x60;2015&#x60;)
     * @param {Object} opts Optional parameters
     * @param {String} opts.trim Use *&#x60;slug&#x60;* from _**&#x60;GET /trims/&#x60;**_ methods here. (e.g. &#x60;20-dla-gg2w-iii-restyling&#x60;)
     * @param {Boolean} opts.onlyOem Show only original equipment wheels
     * @param {String} opts.lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only
     * @param {module:api/SearchApi~searchByModelListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Vehicle>}
     */
    this.searchByModelList = function(make, model, year, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'make' is set
      if (make === undefined || make === null) {
        throw new Error("Missing the required parameter 'make' when calling searchByModelList");
      }

      // verify the required parameter 'model' is set
      if (model === undefined || model === null) {
        throw new Error("Missing the required parameter 'model' when calling searchByModelList");
      }

      // verify the required parameter 'year' is set
      if (year === undefined || year === null) {
        throw new Error("Missing the required parameter 'year' when calling searchByModelList");
      }


      var pathParams = {
      };
      var queryParams = {
        'make': make,
        'model': model,
        'year': year,
        'trim': opts['trim'],
        'only_oem': opts['onlyOem'],
        'lang': opts['lang'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['user_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Vehicle];

      return this.apiClient.callApi(
        '/search/by_model/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the searchByRimList operation.
     * @callback module:api/SearchApi~searchByRimListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MakeWithModels>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find models matching given rim parameters
     * Get a list of model modifications that match the given rim parameters, grouped by manufacturer.  It&#39;s an alias for _**&#x60;GET /bolt-patterns/{bolt_pattern}/&#x60;**_        method with given path and query parameters.
     * @param {String} boltPattern Bolt pattern combines number of stud holes and pitch circle diameter. Use _**&#x60;GET /bolt-patterns/&#x60;**_ to get possible values (e.g. &#x60;5x105&#x60;)
     * @param {Number} rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;)
     * @param {Number} rimWidth Rim width, in (e.g. &#x60;7&#x60;)
     * @param {Object} opts Optional parameters
     * @param {Number} opts.offset Rim offset, mm (e.g. &#x60;40&#x60;)
     * @param {Number} opts.offsetMin Lower bound for rim offset, mm (e.g. &#x60;35&#x60;)
     * @param {Number} opts.offsetMax Upper bound for rim offset, mm (e.g. &#x60;45&#x60;)
     * @param {Number} opts.cb Centre bore value, mm (e.g. &#x60;60&#x60;)
     * @param {Number} opts.cbMin Lower bound for centre bore value, mm (e.g. &#x60;55&#x60;)
     * @param {Number} opts.cbMax Upper bound for centre bore value, mm (e.g. &#x60;65&#x60;)
     * @param {String} opts.lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only
     * @param {String} opts.brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;)
     * @param {String} opts.brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;)
     * @param {String} opts.countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;)
     * @param {String} opts.countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;)
     * @param {module:api/SearchApi~searchByRimListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MakeWithModels>}
     */
    this.searchByRimList = function(boltPattern, rimDiameter, rimWidth, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'boltPattern' is set
      if (boltPattern === undefined || boltPattern === null) {
        throw new Error("Missing the required parameter 'boltPattern' when calling searchByRimList");
      }

      // verify the required parameter 'rimDiameter' is set
      if (rimDiameter === undefined || rimDiameter === null) {
        throw new Error("Missing the required parameter 'rimDiameter' when calling searchByRimList");
      }

      // verify the required parameter 'rimWidth' is set
      if (rimWidth === undefined || rimWidth === null) {
        throw new Error("Missing the required parameter 'rimWidth' when calling searchByRimList");
      }


      var pathParams = {
      };
      var queryParams = {
        'bolt_pattern': boltPattern,
        'rim_diameter': rimDiameter,
        'rim_width': rimWidth,
        'offset': opts['offset'],
        'offset_min': opts['offsetMin'],
        'offset_max': opts['offsetMax'],
        'cb': opts['cb'],
        'cb_min': opts['cbMin'],
        'cb_max': opts['cbMax'],
        'lang': opts['lang'],
        'brands': opts['brands'],
        'brands_exclude': opts['brandsExclude'],
        'countries': opts['countries'],
        'countries_exclude': opts['countriesExclude'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['user_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [MakeWithModels];

      return this.apiClient.callApi(
        '/search/by_rim/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the searchByTireList operation.
     * @callback module:api/SearchApi~searchByTireListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MakeWithModels>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find models matching given tire parameters
     * Get a list of model modifications matching given tire, grouped by manufacturer.  It&#39;s an alias for _**&#x60;GET /tire/{tire}/&#x60;**_ method  (tire configuration is combined of required tire width, aspect ratio and rim diameter).
     * @param {Number} tireWidth Tire width, mm (e.g. &#x60;195&#x60;)
     * @param {Number} aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;)
     * @param {Number} rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;)
     * @param {Object} opts Optional parameters
     * @param {String} opts.lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only
     * @param {String} opts.brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;)
     * @param {String} opts.brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;)
     * @param {String} opts.countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;)
     * @param {String} opts.countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;)
     * @param {module:api/SearchApi~searchByTireListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MakeWithModels>}
     */
    this.searchByTireList = function(tireWidth, aspectRatio, rimDiameter, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'tireWidth' is set
      if (tireWidth === undefined || tireWidth === null) {
        throw new Error("Missing the required parameter 'tireWidth' when calling searchByTireList");
      }

      // verify the required parameter 'aspectRatio' is set
      if (aspectRatio === undefined || aspectRatio === null) {
        throw new Error("Missing the required parameter 'aspectRatio' when calling searchByTireList");
      }

      // verify the required parameter 'rimDiameter' is set
      if (rimDiameter === undefined || rimDiameter === null) {
        throw new Error("Missing the required parameter 'rimDiameter' when calling searchByTireList");
      }


      var pathParams = {
      };
      var queryParams = {
        'tire_width': tireWidth,
        'aspect_ratio': aspectRatio,
        'rim_diameter': rimDiameter,
        'lang': opts['lang'],
        'brands': opts['brands'],
        'brands_exclude': opts['brandsExclude'],
        'countries': opts['countries'],
        'countries_exclude': opts['countriesExclude'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['user_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [MakeWithModels];

      return this.apiClient.callApi(
        '/search/by_tire/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
