/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MakeWithModels', 'model/Tire'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/MakeWithModels'), require('../model/Tire'));
  } else {
    // Browser globals (root is window)
    if (!root.ws_api_client) {
      root.ws_api_client = {};
    }
    root.ws_api_client.TiresApi = factory(root.ws_api_client.ApiClient, root.ws_api_client.MakeWithModels, root.ws_api_client.Tire);
  }
}(this, function(ApiClient, MakeWithModels, Tire) {
  'use strict';

  /**
   * Tires service.
   * @module api/TiresApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TiresApi. 
   * @alias module:api/TiresApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the tiresList operation.
     * @callback module:api/TiresApi~tiresListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Tire>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of tires
     * Get a list of tires with a number of matching model modifications
     * @param {Object} opts Optional parameters
     * @param {Number} opts.width Tire width, mm (e.g. &#x60;195&#x60;)
     * @param {Number} opts.widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;)
     * @param {Number} opts.widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;)
     * @param {Number} opts.aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;)
     * @param {Number} opts.aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;)
     * @param {Number} opts.aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;)
     * @param {Number} opts.rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;)
     * @param {Number} opts.rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;)
     * @param {Number} opts.rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;)
     * @param {String} opts.brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;)
     * @param {String} opts.brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;)
     * @param {String} opts.countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;)
     * @param {String} opts.countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;)
     * @param {module:api/TiresApi~tiresListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Tire>}
     */
    this.tiresList = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'width': opts['width'],
        'width_min': opts['widthMin'],
        'width_max': opts['widthMax'],
        'aspect_ratio': opts['aspectRatio'],
        'aspect_ratio_min': opts['aspectRatioMin'],
        'aspect_ratio_max': opts['aspectRatioMax'],
        'rim_diameter': opts['rimDiameter'],
        'rim_diameter_min': opts['rimDiameterMin'],
        'rim_diameter_max': opts['rimDiameterMax'],
        'brands': opts['brands'],
        'brands_exclude': opts['brandsExclude'],
        'countries': opts['countries'],
        'countries_exclude': opts['countriesExclude'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['user_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Tire];

      return this.apiClient.callApi(
        '/tires/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the tiresRead operation.
     * @callback module:api/TiresApi~tiresReadCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MakeWithModels>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Model modifications matching given tire
     * Get a list of model modifications by tire
     * @param {String} tire Formatted tire size. Use _**&#x60;GET /tires/&#x60;**_ to get possible values (e.g. &#x60;195/50R15&#x60;)
     * @param {Object} opts Optional parameters
     * @param {Number} opts.width Tire width, mm (e.g. &#x60;195&#x60;)
     * @param {Number} opts.widthMin Lower bound for tire width, mm (e.g. &#x60;165&#x60;)
     * @param {Number} opts.widthMax Upper bound for tire width, mm (e.g. &#x60;200&#x60;)
     * @param {Number} opts.aspectRatio Aspect ratio, % (e.g. &#x60;50&#x60;)
     * @param {Number} opts.aspectRatioMin Lower bound for aspect ratio, % (e.g. &#x60;30&#x60;)
     * @param {Number} opts.aspectRatioMax Upper bound for aspect ratio, % (e.g. &#x60;70&#x60;)
     * @param {Number} opts.rimDiameter Rim diameter, in (e.g. &#x60;16&#x60;)
     * @param {Number} opts.rimDiameterMin Lower bound for rim diameter, in (e.g. &#x60;13&#x60;)
     * @param {Number} opts.rimDiameterMax Upper bound for rim diameter, in (e.g. &#x60;20&#x60;)
     * @param {String} opts.lang Use this parameter anywhere in the API to get *&#x60;name&#x60;* field translation of the following objects: **&#x60;Make&#x60;**, **&#x60;Model&#x60;**, **&#x60;Market&#x60;**. Across the *&#x60;name&#x60;* this objects will have *&#x60;name_en&#x60;* field with original english name. By default &#x60;en&#x60; language is used.  Available languages: &#x60;en,de,ru,es,pt,fr,ja,zh-cn,zh-tw&#x60;. Currently translation works for chinese &#x60;zh-cn&#x60; language only
     * @param {String} opts.brands Show information only for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;mitsubishi,nissan,toyota&#x60;)
     * @param {String} opts.brandsExclude Don&#39;t show information for specified manufacturers. Use _**&#x60;GET /makes/&#x60;**_ method to get the full list. (e.g. &#x60;geely,great-wall&#x60;)
     * @param {String} opts.countries Show information for local manufacturers from specified countries only. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;us,gb,jp&#x60;)
     * @param {String} opts.countriesExclude Don&#39;t show information for local manufacturers from specified countries. Use _**&#x60;GET /countries/&#x60;**_ method to get the full list of countries. (e.g. &#x60;ru,ua&#x60;)
     * @param {module:api/TiresApi~tiresReadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MakeWithModels>}
     */
    this.tiresRead = function(tire, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'tire' is set
      if (tire === undefined || tire === null) {
        throw new Error("Missing the required parameter 'tire' when calling tiresRead");
      }


      var pathParams = {
        'tire': tire
      };
      var queryParams = {
        'width': opts['width'],
        'width_min': opts['widthMin'],
        'width_max': opts['widthMax'],
        'aspect_ratio': opts['aspectRatio'],
        'aspect_ratio_min': opts['aspectRatioMin'],
        'aspect_ratio_max': opts['aspectRatioMax'],
        'rim_diameter': opts['rimDiameter'],
        'rim_diameter_min': opts['rimDiameterMin'],
        'rim_diameter_max': opts['rimDiameterMax'],
        'lang': opts['lang'],
        'brands': opts['brands'],
        'brands_exclude': opts['brandsExclude'],
        'countries': opts['countries'],
        'countries_exclude': opts['countriesExclude'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['user_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [MakeWithModels];

      return this.apiClient.callApi(
        '/tires/{tire}/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
