/**
 * Wheel Fitment API
 * The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.
 *
 * OpenAPI spec version: v1
 * Contact: info@wheel-size.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ws_api_client);
  }
}(this, function(expect, ws_api_client) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ws_api_client.Vehicle();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Vehicle', function() {
    it('should create an instance of Vehicle', function() {
      // uncomment below and update the code to test Vehicle
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be.a(ws_api_client.Vehicle);
    });

    it('should have the property market (base name: "market")', function() {
      // uncomment below and update the code to test the property market
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property trim (base name: "trim")', function() {
      // uncomment below and update the code to test the property trim
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property generation (base name: "generation")', function() {
      // uncomment below and update the code to test the property generation
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property studHoles (base name: "stud_holes")', function() {
      // uncomment below and update the code to test the property studHoles
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property pcd (base name: "pcd")', function() {
      // uncomment below and update the code to test the property pcd
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property centreBore (base name: "centre_bore")', function() {
      // uncomment below and update the code to test the property centreBore
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property lockType (base name: "lock_type")', function() {
      // uncomment below and update the code to test the property lockType
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property lockText (base name: "lock_text")', function() {
      // uncomment below and update the code to test the property lockText
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property boltPattern (base name: "bolt_pattern")', function() {
      // uncomment below and update the code to test the property boltPattern
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property power (base name: "power")', function() {
      // uncomment below and update the code to test the property power
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property fuel (base name: "fuel")', function() {
      // uncomment below and update the code to test the property fuel
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

    it('should have the property wheels (base name: "wheels")', function() {
      // uncomment below and update the code to test the property wheels
      //var instance = new ws_api_client.Vehicle();
      //expect(instance).to.be();
    });

  });

}));
